const options = {
  lang: "auto",
  background: "rgba(171, 184, 195, 1)",
  theme: "dracula",
  font: "Hack",
  "window-controls": true,
  "width-adjustment": true,
  line: true,
  "first-line": 1,
  watermark: false,
};

const themes = [
  "3024-night",
  "a11y-dark",
  "base16-dark",
  "base16-light",
  "blackboard",
  "cobalt",
  "dracula-pro",
  "duotone-dark",
  "hopscotch",
  "lucario",
  "material",
  "monokai",
  "night-owl",
  "nord",
  "oceanic-next",
  "one-dark",
  "one-light",
  "panda-syntax",
  "paraiso-dark",
  "seti",
  "shades-of-purple",
  "solarized dark",
  "solarized light",
  "synthwave-84",
  "twilight",
  "vscode",
  "verminal",
  "yeti",
  "zenburn",
];

const langs = [
  "auto",
  "c",
  "css",
  "cpp",
  "go",
  "html",
  "java",
  "javascript",
  "jsx",
  "php",
  "python",
  "rust",
  "typescript",
];

const fonts = [
  "Anonymous-Pro",
  "Cascadia-Code",
  "Droid-Sans-Mono",
  "Fantasque-Sans-Mono",
  "Fira-Code",
  "Hack",
  "IBM-Plex-Mono",
  "Inconsolata",
  "JetBrains-Mono",
  "Monoid",
  "Source-Code-Pro",
  "Space-Mono",
  "Ubuntu-Mono",
];

module.exports = { options, themes, langs, fonts };
